import Head from "next/head";
import localFont from "next/font/local";
import Images from "next/image";
import Navigation from "@/components/navigation";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>CIPTIM LAUNDRY</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      {/* ADVANTAGE START */}
      {/* ADVANTAGE START */}
      <section class="advantage-section">
        <div class="wrapper row">
          <div class="content col-lg-3">
            <h2>LOKASI STRATEGIS</h2>
            <Images
              src="/assets/images/icon/lokasi.jpeg"
              width={300} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores
              ab laborum suscipit, sequi animi iure nisi eligendi neque quaerat
              expedita autem doloribus quod sunt libero?
            </p>
          </div>
          <div class="content col-lg-3">
            <h3>KUALITAS LAYANAN TERJAMIN</h3>
            <Images
              src="/assets/images/icon/service.jpeg"
              width={300} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores
              ab laborum suscipit, sequi animi iure nisi eligendi neque quaerat
              expedita autem doloribus quod sunt libero?
            </p>
          </div>
          <div class="content col-lg-3">
            <h2>PILIHAN YANG BERAGAM</h2>
            <Images
              src="/assets/images/icon/beragam.jpeg"
              width={300} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />
            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maiores
              ab laborum suscipit, sequi animi iure nisi eligendi neque quaerat
              expedita autem doloribus quod sunt libero?
            </p>
          </div>
        </div>
      </section>
      {/* ADVANTAGE END */}
      {/* ADVANTAGE END */}

      {/* SERVICE START */}
      {/* SERVICE START */}
      <section class="service-section">
        <div class="wrapper row">
          <h1 class="m-3">Layanan Kami</h1>
          <div class="content col-lg-3">
            <Images
              src="/assets/images/icon/OpeningCabang.jpeg"
              width={200} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />{" "}
            <p>Laundry kiloan dan satuan</p>
          </div>
          <div class="content col-lg-3">
            <Images
              src="/assets/images/icon/LaundryTas&Sepatu.jpeg"
              width={200} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />{" "}
            <p>Laundry shoe & bag care</p>
          </div>
          <div class="content col-lg-3">
            <Images
              src="/assets/images/icon/IconSetrikaUap.jpeg"
              width={200} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />{" "}
            <p>Ironing</p>
          </div>
          <div class="content col-lg-3">
            <Images
              src="/assets/images/icon/Dry Clean.jpeg"
              width={200} // Sesuaikan lebar gambar
              height={500} // Sesuaikan tinggi gambar
              className="img-fluid "
              alt="LOGO CIPTIM"
            />{" "}
            <p>Dry cleaning</p>
          </div>
        </div>
      </section>
      {/* SERVICE END */}
      {/* SERVICE END */}
      <Footer />
    </>
  );
}
